spring:
  application:
    name: app

  datasource:
    url: jdbc:mysql://localhost:3306/primitive_community?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rootroot

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect